# Generated by Django 3.1.3 on 2020-11-22 20:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('pd_agreement', models.BooleanField(verbose_name='Согласие на обработку')),
                ('email_send', models.BooleanField(verbose_name='Статус отправки письма')),
                ('email_status', models.BooleanField(verbose_name='Статус доставки письма')),
                ('staff_id', models.CharField(max_length=50, verbose_name='id Персонала')),
                ('staff_fullname', models.CharField(max_length=50, verbose_name='Имя и Фамилия персонала')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
                ('event', models.CharField(choices=[('фм', 'Футбольный матч'), ('хм', 'Хоккейный матч'), ('кз', 'Концерт звезды'), ('др', "'Другое")], max_length=2, verbose_name='Событие')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Анкета участников',
                'verbose_name_plural': 'Анкеты участников',
            },
        ),
    ]
