# Generated by Django 3.1.3 on 2020-11-29 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='staff_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='id Персонала'),
        ),
    ]
