# Generated by Django 3.1.3 on 2020-11-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userforms', '0002_auto_20201129_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='staff_fullname',
        ),
    ]
