# Generated by Django 3.1.3 on 2020-12-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excursions', '0004_auto_20201204_1127'),
        ('userforms', '0003_remove_userform_staff_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='excursion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='excursions.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='id Персонала'),
        ),
        migrations.AlterUniqueTogether(
            name='userform',
            unique_together={('first_name', 'last_name')},
        ),
    ]
