# Generated by Django 3.1.3 on 2020-11-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('begining', models.TimeField(default=None, help_text='Укажите начало экскурсий', verbose_name='Начало экскурсий')),
                ('end', models.TimeField(default=None, help_text='Укажите конец экскурсий', verbose_name='Конец экскурсий')),
            ],
            options={
                'verbose_name': 'Расписание экскурсии',
                'verbose_name_plural': 'Расписание экскурсий',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_visitors', models.PositiveIntegerField(default=15, verbose_name='Максимальное число участников')),
                ('number_of_visitors', models.PositiveIntegerField(default=0, verbose_name='Максимальное число участников')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('is_avaliable', models.BooleanField(default=0, verbose_name='Доступность регистрации')),
                ('is_shown', models.BooleanField(default=0, verbose_name='Отображаем ли в аптеке')),
                ('title', models.CharField(max_length=50, verbose_name='Название экскурсии')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excursions.excursionpattern', verbose_name='Паттерн')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
    ]
