# Generated by Django 3.1.3 on 2020-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='number_of_visitors',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущее количество участников'),
        ),
        migrations.AlterUniqueTogether(
            name='excursion',
            unique_together={('pattern', 'start_datetime'), ('pattern', 'end_datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='excursionpattern',
            unique_together={('weekday', 'begining')},
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='title',
        ),
    ]
