# Generated by Django 3.1.3 on 2020-12-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_auto_20201129_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='is_shown',
            field=models.BooleanField(default=0, verbose_name='Отображаемость'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='pattern',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.SET_DEFAULT, to='excursions.excursionpattern', verbose_name='Паттерн'),
        ),
        migrations.AlterField(
            model_name='excursionpattern',
            name='weekday',
            field=models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье'), (0, 'НЕТ В РАСПИСАНИИ')], verbose_name='День недели'),
        ),
    ]
