# Generated by Django 3.1.3 on 2020-12-04 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Надпись на кнопке')),
                ('position', models.SmallIntegerField(verbose_name='Позиция кнопки')),
                ('href', models.CharField(max_length=200, verbose_name='Ссылка или действие')),
                ('class_of', models.CharField(max_length=50, verbose_name='Класс')),
                ('available_for', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь для')),
            ],
            options={
                'verbose_name': 'IndexButton',
                'verbose_name_plural': 'IndexButtons',
                'ordering': ['position'],
            },
        ),
    ]
