# Generated by Django 3.1.3 on 2020-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbutton',
            name='available_for',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Группа пользователей'),
        ),
    ]
